# Generated by Django 4.1.7 on 2023-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vechile',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Sm', 'Small'), ('Md', 'Medium'), ('La', 'Large')], max_length=2),
        ),
    ]
